import type { AchievementCategory, AchievementDef } from '@/lib/progression/models/types';

const T = [
  { target: 1, coinReward: 2, xpReward: 2 },
  { target: 5, coinReward: 5, xpReward: 5 },
  { target: 10, coinReward: 10, xpReward: 10 },
] as const;

const T_SMALL = [
  { target: 1, coinReward: 2, xpReward: 2 },
  { target: 2, coinReward: 5, xpReward: 5 },
  { target: 3, coinReward: 10, xpReward: 10 },
] as const;

export const ACHIEVEMENT_CATALOG: readonly AchievementDef[] = [
  {
    id: 'ach_first_booking',
    category: 'booking',
    titleAr: 'أول حجز',
    descriptionAr: 'أكمل حجوزاتك — 3 مستويات',
    criteria: { completedBookings: 10 },
    tiers: [...T_SMALL],
  },
  {
    id: 'ach_booking_streak',
    category: 'booking',
    titleAr: 'حجوزات متتالية',
    descriptionAr: 'حافظ على نشاط الحجز',
    criteria: { completedBookings: 10 },
    tiers: [...T],
  },
  {
    id: 'ach_customers_25',
    category: 'booking',
    titleAr: 'زبون مخلص',
    descriptionAr: 'أكمل عدة حجوزات',
    criteria: { completedBookings: 25 },
    tiers: [
      { target: 3, coinReward: 2, xpReward: 2 },
      { target: 10, coinReward: 5, xpReward: 5 },
      { target: 25, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_customers_100',
    category: 'booking',
    titleAr: '100 حجز',
    descriptionAr: 'وصل لمئة حجز مكتمل',
    criteria: { completedBookings: 100 },
    tiers: [
      { target: 10, coinReward: 2, xpReward: 2 },
      { target: 50, coinReward: 5, xpReward: 5 },
      { target: 100, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_first_review',
    category: 'quality',
    titleAr: 'أول تقييم',
    descriptionAr: 'قيّم تجربتك',
    criteria: { reviews: 10 },
    tiers: [...T],
  },
  {
    id: 'ach_reviews_25',
    category: 'quality',
    titleAr: 'مقيّم نشط',
    descriptionAr: 'شارك آراءك بانتظام',
    criteria: { reviews: 25 },
    tiers: [
      { target: 3, coinReward: 2, xpReward: 2 },
      { target: 10, coinReward: 5, xpReward: 5 },
      { target: 25, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_first_comment',
    category: 'community',
    titleAr: 'أول تعليق',
    descriptionAr: 'شارك في النقاش',
    criteria: { forumComments: 10 },
    tiers: [...T],
  },
  {
    id: 'ach_first_post',
    category: 'community',
    titleAr: 'أول منشور',
    descriptionAr: 'انشر في المنتدى',
    criteria: { forumPosts: 10 },
    tiers: [...T],
  },
  {
    id: 'ach_forum_active',
    category: 'community',
    titleAr: 'عضو نشط',
    descriptionAr: 'تفاعل في المجتمع',
    criteria: { forumPosts: 20 },
    tiers: [
      { target: 2, coinReward: 2, xpReward: 2 },
      { target: 8, coinReward: 5, xpReward: 5 },
      { target: 20, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_transformation',
    category: 'community',
    titleAr: 'تحولات قبل/بعد',
    descriptionAr: 'شارك أعمالك',
    criteria: { forumPosts: 5 },
    tiers: [...T_SMALL],
  },
  {
    id: 'ach_referrals',
    category: 'growth',
    titleAr: 'دعوات الأصدقاء',
    descriptionAr: 'شارك رابط الدعوة',
    criteria: { referralShares: 10 },
    tiers: [...T],
  },
  {
    id: 'ach_referrals_25',
    category: 'growth',
    titleAr: 'سفير حلاقي',
    descriptionAr: 'انشر المنصة باستمرار',
    criteria: { referralShares: 25 },
    tiers: [
      { target: 3, coinReward: 2, xpReward: 2 },
      { target: 12, coinReward: 5, xpReward: 5 },
      { target: 25, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_streak_7',
    category: 'streak',
    titleAr: 'سلسلة أسبوع',
    descriptionAr: '7 أيام متتالية',
    criteria: { streakDays: 7 },
    tiers: [
      { target: 2, coinReward: 2, xpReward: 2 },
      { target: 4, coinReward: 5, xpReward: 5 },
      { target: 7, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_streak_30',
    category: 'streak',
    titleAr: 'سلسلة شهر',
    descriptionAr: '30 يوماً متتالياً',
    criteria: { streakDays: 30 },
    tiers: [
      { target: 7, coinReward: 2, xpReward: 2 },
      { target: 15, coinReward: 5, xpReward: 5 },
      { target: 30, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_barber_jobs',
    category: 'barber',
    titleAr: 'حلاق محترف',
    descriptionAr: 'أكمل حجوزات عملائك',
    criteria: { completedBookings: 50 },
    tiers: [
      { target: 5, coinReward: 2, xpReward: 2 },
      { target: 20, coinReward: 5, xpReward: 5 },
      { target: 50, coinReward: 10, xpReward: 10 },
    ],
  },
  {
    id: 'ach_gallery',
    category: 'barber',
    titleAr: 'معرض الأعمال',
    descriptionAr: 'أكمل معرض صورك',
    criteria: { galleryCompleted: true },
    tiers: [...T_SMALL],
  },
  {
    id: 'ach_marketplace',
    category: 'marketplace',
    titleAr: 'متسوق نشط',
    descriptionAr: 'تصفح منتجات السوق',
    criteria: { forumPosts: 1 },
    tiers: [...T_SMALL],
  },
  {
    id: 'ach_social',
    category: 'social',
    titleAr: 'تواصل اجتماعي',
    descriptionAr: 'تابع حلاقين وشارك',
    criteria: { referralShares: 5 },
    tiers: [...T_SMALL],
  },
] as const;

export const ACHIEVEMENT_CATEGORY_LABELS: Record<AchievementCategory, string> = {
  booking: 'الحجوزات',
  community: 'المجتمع',
  growth: 'الدعوات والنمو',
  streak: 'السلاسل',
  barber: 'الحلاقين',
  marketplace: 'السوق',
  quality: 'الجودة',
  social: 'التواصل',
};
