import type { BadgeCategory, BadgeDef } from '@/lib/progression/models/types';

export const BADGE_CATALOG: readonly BadgeDef[] = [
  {
    id: 'first_booking',
    category: 'booking' as BadgeCategory,
    audience: ['client'],
    nameAr: 'أول حجز',
    descriptionAr: 'أكملت أول موعد عبر حلاقي',
    emoji: '✂️',
    color: '#0F766E',
    criteria: { completedBookings: 1 },
    xpBonus: 15,
  },
  {
    id: 'bookings_10',
    category: 'booking',
    audience: ['client'],
    nameAr: '10 حجوزات',
    descriptionAr: 'أكملت 10 مواعيد',
    emoji: '🔟',
    color: '#0F766E',
    criteria: { completedBookings: 10 },
    xpBonus: 25,
  },
  {
    id: 'bookings_50',
    category: 'booking',
    audience: ['client'],
    nameAr: '50 حجزاً',
    descriptionAr: 'أكملت 50 موعداً',
    emoji: '💎',
    color: '#0F766E',
    criteria: { completedBookings: 50 },
    xpBonus: 50,
  },
  {
    id: 'bookings_100',
    category: 'booking',
    audience: ['client'],
    nameAr: '100 حجز',
    descriptionAr: 'أكملت 100 موعد',
    emoji: '👑',
    color: '#0F766E',
    criteria: { completedBookings: 100 },
    xpBonus: 100,
  },
  {
    id: 'trusted',
    category: 'verification',
    audience: ['barber'],
    nameAr: 'موثوق',
    descriptionAr: 'حساب موثوق على حلاقي',
    emoji: '🛡️',
    color: '#2563EB',
    criteria: { trusted: true },
    xpBonus: 20,
  },
  {
    id: 'verified',
    category: 'verification',
    audience: ['barber', 'client', 'store', 'doctor'],
    nameAr: 'موثّق',
    descriptionAr: 'تم التحقق من هويتك',
    emoji: '✅',
    color: '#059669',
    criteria: { verified: true },
    xpBonus: 20,
  },
  {
    id: 'content_creator',
    category: 'community',
    audience: ['client'],
    nameAr: 'صانع محتوى',
    descriptionAr: 'نشرت عدة مواضيع في المنتدى',
    emoji: '✍️',
    color: '#7C3AED',
    criteria: { forumPosts: 5 },
    xpBonus: 25,
  },
  {
    id: 'ambassador',
    category: 'referral',
    nameAr: 'سفير',
    descriptionAr: 'دعوت عدة أصدقاء',
    emoji: '🎁',
    color: '#DB2777',
    criteria: { referralShares: 5 },
    xpBonus: 40,
  },
  {
    id: 'early_supporter',
    category: 'seasonal',
    nameAr: 'داعم مبكر',
    descriptionAr: 'انضممت في مرحلة الإطلاق',
    emoji: '🌱',
    color: '#D97706',
    criteria: { earlySupporter: true },
    xpBonus: 15,
  },
  {
    id: 'gallery_master',
    category: 'gallery',
    audience: ['barber'],
    nameAr: 'سيد المعرض',
    descriptionAr: 'أكملت معرض أعمالك',
    emoji: '🖼️',
    color: '#EA580C',
    criteria: { galleryCompleted: true },
    xpBonus: 50,
  },
  {
    id: 'streak_7',
    category: 'streak',
    nameAr: 'سلسلة أسبوع',
    descriptionAr: '7 أيام متتالية',
    emoji: '🔥',
    color: '#EA580C',
    criteria: { streakDays: 7 },
    xpBonus: 20,
  },
  {
    id: 'streak_30',
    category: 'streak',
    nameAr: 'سلسلة شهر',
    descriptionAr: '30 يوماً متتالياً',
    emoji: '🔥',
    color: '#DC2626',
    criteria: { streakDays: 30 },
    xpBonus: 40,
  },
  {
    id: 'streak_100',
    category: 'streak',
    nameAr: 'سلسلة 100',
    descriptionAr: '100 يوم متتالٍ',
    emoji: '🔥',
    color: '#B91C1C',
    criteria: { streakDays: 100 },
    xpBonus: 80,
  },
  {
    id: 'streak_365',
    category: 'streak',
    audience: ['client'],
    nameAr: 'سلسلة سنة',
    descriptionAr: '365 يوماً متتالياً',
    emoji: '🏆',
    color: '#7F1D1D',
    criteria: { streakDays: 365 },
    xpBonus: 200,
  },
  {
    id: 'barber_jobs_50',
    category: 'booking',
    audience: ['barber'],
    nameAr: '50 عميلاً',
    descriptionAr: 'أكملت 50 حجزاً كحلاق',
    emoji: '💈',
    color: '#0F766E',
    criteria: { completedBookings: 50 },
    xpBonus: 60,
  },
  {
    id: 'store_trusted',
    category: 'verification',
    audience: ['store'],
    nameAr: 'متجر موثوق',
    descriptionAr: 'متجر معتمد على حلاقي',
    emoji: '🏪',
    color: '#2563EB',
    criteria: { trusted: true },
    xpBonus: 25,
  },
  {
    id: 'doctor_care',
    category: 'verification',
    audience: ['doctor'],
    nameAr: 'رعاية موثوقة',
    descriptionAr: 'ملف طبي موثّق على حلاقي',
    emoji: '🩺',
    color: '#059669',
    criteria: { verified: true },
    xpBonus: 25,
  },
] as const;

export const MAX_PINNED_BADGES = 8;
